LegoAppToolsWebApp/Controllers/ProcessFileController.cs
//#define TESTING

using LegoAppToolsLib;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;

namespace LegoAppToolsWebApp.Controllers
{
    using LegoAppCodeListing = List<string>;
    using LegoAppStatsList = Dictionary<string, string>;

    /// <summary>
    /// Simple service to fix corrupt SPIKE/Robot Inventor/EV3 Classroom files
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class ProcessFileController : ControllerBase
    {
        private readonly ILogger<ProcessFileController> _logger;
#if TESTING
        private readonly IWebHostEnvironment _webHostEnvironment;
#endif
        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="logger"></param>
        public ProcessFileController(ILogger<ProcessFileController> logger, IWebHostEnvironment webHostEnvironment)
        {
#if TESTING
            _webHostEnvironment = webHostEnvironment;
#endif
            _logger = logger;
        }

        [HttpPost]
        public IActionResult ProcessFile([FromForm] IFormFile file, [FromForm] string selectedpart, [FromForm] string selectedtab)
        {
#if TESTING
#else
            //-- exit if there are no files
            if (file == null || file.Length == 0)
                return Content("file not selected");
#endif

            switch (selectedtab)
            {
                case "repair":
                    return RepairFile(file, selectedpart);
                case "screenshot":
                    return ScreenshotFile(file);
                case "preview":
                    return Preview(file);
                case "machinelearning_preview":
                    return MachineLearningPreview(file);
            }
            return BadRequest();
        }

        /// <summary>
        /// Preview Machine learning samples
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public IActionResult MachineLearningPreview(IFormFile file)
        {
            try
            {
                Stream stream1 = file?.OpenReadStream();
#if TESTING
                string webRootPath = _webHostEnvironment.WebRootPath;
                string contentRootPath = _webHostEnvironment.ContentRootPath;
                var filename = @"sample\MLearning1.lms";
                var afilename = Path.Combine(contentRootPath, filename);
                stream1 = System.IO.File.OpenRead(afilename);
#endif

                //dynamic eo = new ExpandoObject();
                JObject result = new JObject();
                var mlresults = LegoAppTools.GetFileMachineLearningImages(stream1);
                foreach (var kvp in mlresults)
                {
                    //eo[kvp.Key] = kvp.Value.Count.ToString();

                    var joa2 = new JArray();
                    kvp.Value.ForEach(mlitem =>
                    {
                        var jo2 = new JObject();
                        jo2["filename"] = mlitem.Filename;
                        jo2["size"] = mlitem.Size;
                        MemoryStream ms = new MemoryStream(); mlitem.Stream.Position = 0; mlitem.Stream.CopyTo(ms);
                        jo2["image"] = Convert.ToBase64String(ms.ToArray());
                        joa2.Add(jo2);
                    });
                    result[kvp.Key] = joa2;
                }
                return Content(result.ToString());
            }
            catch (LegoAppToolException ex)
            {
                return ValidationProblem(ex.Message);
            }
        }


        /// <summary>
        /// Service to returna  compined preview json
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public IActionResult Preview(IFormFile file)
        {
            //-- repair the file
            try
            {
                JObject result = new JObject();
                Stream stream1 = file?.OpenReadStream();

#if TESTING
                string webRootPath = _webHostEnvironment.WebRootPath;
                string contentRootPath = _webHostEnvironment.ContentRootPath;
                var filename = @"sample\MLearning1.lms";
                var afilename = Path.Combine(contentRootPath, filename);
                stream1 = System.IO.File.OpenRead(afilename);
#endif

                stream1.Position = 0;
                (LegoAppCodeListing code, LegoAppStatsList stats) = LegoAppTools.GetFileContents(stream1);

                //-- add stats
                result.Add("stats", JObject.FromObject(stats));

                //-- add code
                result.Add("code", string.Join("\r\n", code.ToArray()));

                //-- add svg
                stream1.Position = 0;
                using Stream svgstream = LegoAppTools.GetSVGStreamFromLegoFileStream(stream1);
                using StreamReader sr = new StreamReader(svgstream);
                string svg = sr.ReadToEnd();
                result.Add("svg", svg);

                return Content(result.ToString());
            }
            catch (LegoAppToolException ex)
            {
                return ValidationProblem(ex.Message);
            }
        }

        /// <summary>
        /// Returns a png screenshot
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public IActionResult ScreenshotFile([FromForm] IFormFile file)
        {
            try
            {
                var so_result = LegoAppTools.GeneratePngCanvas(file.OpenReadStream(), file.FileName);

                if (so_result.stream != null)
                    return File(so_result.stream, "image/png", so_result.name);
                else
                    return BadRequest();
            }
            catch (LegoAppToolException ex)
            {
                return ValidationProblem(ex.Message);
            }
        }

        /// <summary>
        /// Upload a corrupted LEGO file and download the repaired file
        /// </summary>
        /// <param name="file">Corrupt LEGO file</param>
        /// <param name="selectedpart">Choose whether 'First' or 'Second' part will be restored</param>
        /// <returns>Repaired LEGO file</returns>
        /// <response code="400">If the LEGO file is already valid or cannot be repaired</response>
        public IActionResult RepairFile([FromForm] IFormFile file, [FromForm] string selectedpart)
        {
            //-- repair the file
            try
            {
                var so_result = LegoAppTools.RepairFile(file.OpenReadStream(), file.FileName, selectedpart == "first");

                if (so_result.stream != null)
                    return File(so_result.stream, "application/zip", so_result.name);
                else
                    return BadRequest();
            }
            catch (LegoAppToolException ex)
            {
                return ValidationProblem(ex.Message);
            }
        }
    }
}

LegoAppToolsWebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace LegoAppToolsBackend.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            
        }
    }
}

LegoAppToolsWebApp/Pages/Index.cshtml
@page
@model LegoAppToolsBackend.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h3>
    LEGO App Tools
    <small class="text-muted">
        various tools to help your life with LEGO apps
    </small>
</h3>

<form asp-controller="ProcessFile" asp-action="ProcessFile" method="post" enctype="multipart/form-data">

    <div id="maincontainer" class="container py-3">

        <div class="flex-fill pb-3">
            <input type="file" name="file" accept=".llsp,.lms,.lmsp" id="file" class="form-control"
                   data-text="Choose a file"
                   data-input="true" data-buttonbefore="true" data-dragdrop="true"
                   data-badge="false" data-placeholder="Select a LEGO SPIKE, Robot Inventor or EV3 Classroom file (.llsp, .lms, .lmsp) to upload" />
        </div>

        <div class="p-3 d-none" style="position:absolute;" id="spinner">
            <div class="spinner-grow text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>

        <div id="tab_dummy" class="h-75 border active py-5">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <i class="bi bi-cloud-arrow-up-fill" style="font-size: 6rem; color: cornflowerblue; line-height: 1em"></i><br />
                    Drop a LEGO SPIKE, Robot Inventor or EV3 Classroom file
                </div>
            </div>
        </div>

        <div id="tabs_main" class="h-100 d-none" style="min-height:30vh;">
            <ul class="nav nav-tabs border-0" role="tablist">
                <li class="nav-item p-2">
                    <svg width="20" height="20">
                        <use id="svg_program_use" href="./img/Cat0.svg#dsmIcon" xlink:href="./img/Cat0.svg#dsmIcon"></use>
                    </svg>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#tab_code" id="code" data-bs-toggle="tab">Code</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tab_svg" id="svg" data-bs-toggle="tab">Preview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tab_stats" id="stats" data-bs-toggle="tab">
                        Stats
                        <i id="stats_icon_warning" class="bi bi-exclamation-triangle-fill d-none" style="color:yellow"></i>
                        <i id="stats_icon_error" class="bi bi-exclamation-triangle-fill d-none" style="color:red"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tab_machinelearning" id="machinelearning" data-bs-toggle="tab">ML</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tab_repair" id="repair" data-bs-toggle="tab">Repair <i class="bi bi-exclamation-triangle-fill"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tab_screenshot" id="screenshot" data-bs-toggle="tab">Screenshot</a>
                </li>
                <li class="nav-item mx-auto">
                </li>
                <li class="nav-item justify-content-end">
                    <button type="submit" id="submitBtn" class="btn btn-primary d-none">Submit File</button>
                </li>
            </ul>

            <div class="tab-content h-75">
                <div id="tab_repair" class="tab-pane p-3 h-100 border disabled _cansubmit">
                    <h3>Repair a corrupt LEGO Classroom / SPIKE / Robot Inventor App file</h3>
                    <div class="text-muted">
                        Sometimes the new LEGO apps mix up files and they cannot be opened anymore. I have created this app to fix files until LEGO service releases a fix for this.
                        Read more about the problem and the solution <a href="https://digitalbrick.home.blog/2022/06/02/bugfixing-a-frozen-lego-spike-prime-llsp-file/">here</a>.
                    </div>
                    <hr />
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="selectedpart" value="first" id="first" checked />
                        <label class="form-check-label" for="first">Restore <u>first</u> part</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="selectedpart" value="second" id="second" />
                        <label class="form-check-label" for="second">Restore <u>second</u> part</label>
                    </div>
                </div>
                <div id="tab_screenshot" class="tab-pane p-3 h-100 border _cansubmit">
                    <h3>Download a program screenshot as PNG</h3>
                    <div>Download a PNG picture with transparent background of the code</div>
                </div>
                <div id="tab_svg" class="tab-pane p-3 h-100 border">
                    <div id="preview_svg"></div>
                </div>
                <div id="tab_stats" class="tab-pane p-3 h-100 border">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Stat</th>
                                <th scope="col">Value</th>
                            </tr>
                        </thead>
                        <tbody id="preview_stats">
                        </tbody>
                    </table>
                </div>
                <div id="tab_code" class="tab-pane p-3 h-100 border active">
                    <pre id="preview_code" style="font-family: 'Courier New', monospace;}"></pre>
                </div>
                <div id="tab_machinelearning" class="tab-pane p-3 h-100 border">
                    <div id="preview_ml"></div>
                </div>
            </div>
        </div>

        <input id="selectedtab" type="hidden" name="selectedtab" value="" />
    </div>

</form>

LegoAppToolsWebApp/Pages/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
<link rel="manifest" href="/favicon/site.webmanifest">
<link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/favicon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/favicon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

LegoAppToolsWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LegoAppTools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await Html.PartialAsync("_Favicons");
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index" style="font-size: 200%; padding-bottom: 0px;">
                    <svg height="1.5em" width="4em" style="position:relative; top:-5px">
                        <use href="./img/logo_full.svg#icon" xlink:href="./img/logo_full.svg#icon"></use>
                    </svg>
                    LEGO App Tools
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Attila Farago - <a href="https://github.com/afarago">@@afarago</a> - 2022
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>